## PR のコメントをトリガーにして、アーティファクトを TestFlight にデプロイする
name: Deploy app to TestFlight

on:
  issue_comment:
    types: [created, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'
  issues: 'write' # PR のコメントに必要となる permission
  pull-requests: 'write' # PR のコメントに必要となる permission
  checks: 'read' # PR の workflow が通っているか確認するために必要となる permission

jobs:
  deploy-test-flight:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/testflight')
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      # コマンドの設定
      - uses: github/command@v1
        id: command
        with:
          command: '/testflight'
          reaction: 'rocket'
          allow_drafts: true
          skip_ci: true
          skip_reviews: true
          permissions: 'none,read,write,maintain,admin' # GitHub App が権限チェックに引っかかるため全ての権限を許可する

      - if: steps.command.outputs.continue == ''
        run: exit 1

      - name: No set an argument
        if: |
          steps.command.outputs.params == '' ||
            !(startsWith(steps.command.outputs.params, 'dev') ||
            startsWith(steps.command.outputs.params, 'stg') ||
            startsWith(steps.command.outputs.params, 'prd'))
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':guardsman: dev, stg, prd のいずれかを指定してください。'
            })
            core.setFailed('無効な引数が設定されています。');

      - name: Find pull request ref with comment
        uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1 # v3.0.0
        id: find-ref

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.find-ref.outputs.head_ref }}

      # デプロイが完了したら PR にコメントする
      - name: Comment to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':airplane: iOS (${{ steps.command.outputs.params }}) アプリを TestFlight へデプロイしました。'
            })
